controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
app_task_update:
    path: /task/update/{id}
    defaults:
        _controller: App\Controller\TaskController::update
    requirements:
        id: '\d+'
